### ISSUE TITLE
Does elaster do a partial update or whole update for existing documents?

### ISSUE THREAD

**Issue by cheenu** [likeastore/elaster#3]
Firstly, thanks for making elaster :+1: !

I have a question - does elaster do a partial or whole update for existing documents?

**Comment by alexbeletsky** [comment]
hi @cheenu - can you please specify, what exactly you mean: update the document in ES?

as you can see https://github.com/likeastore/elaster/blob/master/source/elaster.js#L88, it uses `elastic.create` without checking if this document exist or not. I'm actually not certain of ES behaviour, would it apply update if document with such `id` is already on storage.

**Comment by cheenu** [comment]
Apologies for the delayed reply! It looks like ES would throw an error (http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/create-doc.html) and elaster catches this error and skips to the next document. 

Anyway, got what I needed with a few changes to elaster. Thanks for writing this script!

**Comment by alexbeletsky** [comment]
Welcome!
